### PR TITLE
Allow users to set the selector's color.

### PR DESCRIPTION
**Pull request by noordawod**

### CODE REVIEW

**Review by diegoveloper — APPROVED** [review]
LGTM, thanks again! 

Do you have more changes or do you prefer to release a new version with this change?

**Comment by noordawod** [comment]
You're welcome! No more changes so far mate.
I would love if you can bump up the patch version and release it :)

**Comment by diegoveloper** [comment]
@noordawod oh hmm I can't release yet, is not compiling on my local, this class is not found `CupertinoPickerDefaultSelectionOverlay`  , which version of flutter are you using? I'm on `Channel stable, 1.22.0`

**Comment by noordawod** [comment]
Flutter 1.23.0-14.0.pre.118 • channel master • https://github.com/flutter/flutter.git
Framework • revision 23c7ee9deb (2 hours ago) • 2020-10-12 09:50:30 -0700
Engine • revision 11d756a62e
Tools • Dart 2.11.0 (build 2.11.0-207.0.dev)

Darn... I thought this class was always there.

**Comment by noordawod** [comment]
What do you suggest to do?

**Comment by diegoveloper** [comment]
Change the widget that doesn't exist in stable :)

**Pull request merged**
