### PR TITLE
Properly use the right overlay based on engagement mode.

### PR DESCRIPTION
**Pull request by noordawod**
Works on my end, doctor -v:

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.380, on Linux, locale en_US.utf8)
    • Flutter version 1.22.0-10.0.pre.380 at /home/noor/Google/Flutter
    • Framework revision ec40df9576 (2 days ago), 2020-09-25 21:27:22 -0700
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)
```

### CODE REVIEW

**Review by diegoveloper — COMMENTED** [review]
Mm there are more issues than the color. Please try using `stable` version

**Comment by noordawod** [comment]
Alright. May I ask what version of Flutter are you using?

**Comment by noordawod** [comment]
I know what's the problem now. I'll issue a fix tomorrow, it's very late here.
Very sorry for the mishap, but will fix it asap tomorrow.

**Comment by noordawod** [comment]
GestureDetector's drag start/end is reset when a dialog is presented. So the solution is to use an Overlay when engagement mode is `drag`, and use a Dialog when it is `tap`.

**Comment by diegoveloper** [comment]
I tried on iOS simulator , Flutter (Channel stable, 1.20.3)

**Comment by noordawod** [comment]
Good morning! Patch has been submitted, and tested to work nicely here.
Let me know if you face any more problems :)

**Comment by diegoveloper** [comment]
Thanks, it's working fine now :D

**Comment by noordawod** [comment]
Brilliant! Thank you for the initial version, I love this plugin :) If I have more things, I'll submit more pr's.

**Pull request merged**
