### PR TITLE
Added back button support + refactor

### PR DESCRIPTION
**Pull request by noordawod**
In order to support tapping the Back button, the implementation has to use a Dialog instead of an Overlay. The reason is that the latter transcends the Navigator and thus tapping the back button cannot be intercepted.

I tried keeping all UX as-is, and even fixed a positioning bug when calculating the Y position of the magnified selection widget. As far as I can see, there is no UI difference.

### CODE REVIEW

**Comment by diegoveloper** [comment]
@noordawod thanks again, can you check the conflicting files? I sent some changes to `master` few minutes ago.

**Comment by noordawod** [comment]
Ohh where did that come from... I'll check right away.

**Comment by diegoveloper** [comment]
@noordawod I'm getting some errors running the sample with the latest code:

The first one is:

`showGeneralDialog`

`'package:flutter/src/widgets/routes.dart': Failed assertion: line 1439 pos 14: 'barrierColor != _kTransparent': is not true.
`
we can't use transparent color as a `barrierColor` ,  `barrierColor: Colors.transparent,`

After I remove that line , every time I tap on any dropbox I get these errors:

```dart

VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/routes.dart': Failed assertion: line 1294 pos 12: 'scope != null': is not true.
#0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:36:5)
#2      ModalRoute.willPop 
package:flutter/…/widgets/routes.dart:1294
#3      NavigatorState.maybePop 
package:flutter/…/widgets/navigator.dart:3745
#4      _DirectSelectState._removeOverlay 
package:direct_select/src/widget.dart:121
#5      _DirectSelectState.build.<anonymous closure> 
package:direct_select/src/widget.dart:161
#6      DragGestureRecognizer._checkEnd.<anonymous closure> 
package:flutter/…/gestures/monodrag.dart:441
#7      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:184
#8      DragGestureRecognizer._checkEnd 
package:flutter/…/gestures/monodrag.dart:441
#9      DragGestureRecognizer.didStopTrackingLast<…>

```


This is the method : 
```dart
  Future<void> _removeOverlay() async {
    if (mounted) {
      final navigator = Navigator.of(context);
      if (_dialogShowing && navigator != null) {
// THIS LINE
        if (!await navigator.maybePop()) {
          _notifySelectedItem();
        }
      } else {
        _notifySelectedItem();
      }
      _dialogShowing = false;
    }
  }
```

Tested on iOS simulator using Flutter stable 1.20

**Comment by noordawod** [comment]
On it!

**Comment by noordawod** [comment]
Apologies for this mishap (didn't see it happening for me), let's see if this fixes it for you: https://github.com/diegoveloper/flutter_direct_select/pull/14

**Pull request merged**
